const p = require('E:/knowledge/vault/workbenches/skill-workbench/data/restore-plan.json');
const B = String.fromCharCode(92);
const byName = {};
p.r1.forEach(x => { (byName[x.target] = byName[x.target] || []).push(x.dir.split(B).slice(2, 4).join('/')); });
const names = Object.entries(byName).map(([t, dirs]) => ({ name: t.split(B).pop(), tools: [...new Set(dirs)] }));
console.log('unique vault masters referenced:', names.length);
const multi = names.filter(n => n.tools.length > 1);
console.log('masters linked from >1 tool:', multi.length);
console.log('masters linked from 1 tool only:', names.length - multi.length);
const perTool = {};
p.r1.forEach(x => { const tool = x.dir.split(B)[2]; perTool[tool] = (perTool[tool] || 0) + 1; });
console.log('per tool junction count:', JSON.stringify(perTool));
console.log('single-tool masters:', names.filter(n => n.tools.length === 1).map(n => n.name + '(' + n.tools[0] + ')').join(', '));
console.log('multi-tool masters:', multi.map(n => n.name + '->' + n.tools.join('+')).join(', '));
